# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c45ca0892673302d8a84005ec8498a7fd59ba50e052c13b94672a906f0da68d887abc727665d16c06d5dd401904ebd80433e6b6fecb174fd71e69fcb1e94d883

test:
  secret_key_base: a29db847c421c7f3d705c91bbb675c9761e2e76ba5bf0536ebed654546cac786d54e6de27b7a74fdbd17e4c02937e4b91fd628e7772a9da6b95bbb8580da1d36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
